import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next";

 import { TRPCReactProvider } from "@/trpc/client";
const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html
          lang="en"
          className={`${inter.className} h-full antialiased`}
        >
          <body className="min-h-full flex flex-col">{children}
            <Toaster richColors position="bottom-right" />
          </body>
          
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}
